version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=co_proj
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=co_proj.settings
      - DATABASE_URL=postgresql://postgres:123@db:5432/co_proj
      - DEBUG=1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    stdin_open: true
    tty: true

volumes:
  postgres_data: