# Generated by Django 5.1.2 on 2024-11-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazyn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
